"""empty message

Revision ID: dfddf868fdfd
Revises: 514f5ef032e9
Create Date: 2016-08-08 17:19:29.101413

"""

# revision identifiers, used by Alembic.
revision = 'dfddf868fdfd'
down_revision = '514f5ef032e9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotspot', sa.Column('status', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('role', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('status', sa.String(length=50), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'status')
    op.drop_column('user', 'role')
    op.drop_column('hotspot', 'status')
    ### end Alembic commands ###
